### ISSUE TITLE
Build an App?

### ISSUE THREAD

**Issue by browniefed** [Jobs-Economy/raise-effect#23]
Not sure if it's valuable, but we could build a hack oregon app with React Native? I could help people learn React Native/React as well. For the iOS portion it would require a Mac.

**Comment by danieljwest** [comment]
Would be fun, but we do only have something like 9 days left! So... dunno! Might be best to just target mobile sized devices with bootstrap?

**Comment by browniefed** [comment]
@danieljwest yes, I was thinking more longer term, not for demo night.

**Comment by danieljwest** [comment]
Any excuse to learn a new tech is a good one... so I'd be interested.
