### ISSUE TITLE
Simplify Tech Stack on React

### ISSUE THREAD

**Issue by browniefed** [Jobs-Economy/raise-effect#24]
It seems like we have a mix of Backbone, Handlebars and React. For the sake of outside contribution, we should settle on just using React, including React Router instead of the Backbone routing.

My thoughts include also using [https://github.com/davidguttman/sassify](https://github.com/davidguttman/sassify) to compile our sass as it looks like we're using straight node-sass.

This is of course all depending on priority, if we need to get out features more than tackle tech debt then we should focus on featuers.

**Comment by danieljwest** [comment]
I've been on this project all of 48 hours or so so take my opinion with a grain of salt.

I'm all for simplification. We're barely using Backbone as is, so swapping it out wouldn't be a big problem. I'm not familiar enough to know what sassify would buy us over node-sass, but the effort to swap it doesn't look like much. So, if you think there's enough value in switching over, I'm up for it. Are we actually using Handlebars somewhere? I haven't stumbled across it yet.

I've been struggling with the best way to get data bound to React. Using backbone seems to require a mixin of some sort, which is a little bit eh. What's the preferred method of getting data from the api to the component? 

Anyway I'll see you in a bit!

**Comment by browniefed** [comment]
Seems like we have .hbs files, and are npm installing handelbars and such. Not sure how much is still in use or not. The general accepted practice is a Flux style approach, and Redux is generally the most highly recommended at the moment. 

However we don't need anything too special as we aren't to that scale yet. So we can just use good ole POJOs, no need for backbone or special data binding of any sort.

**Comment by danieljwest** [comment]
Ah yeah I think the template stuff was just there as a stop gap measure as we move toward React. (But I could be wrong) 

Anyway I'll be heading to OMSI shortly!

**Comment by browniefed** [comment]
DONE
