### ISSUE TITLE
React component hierarchy - see comments for description of components below

### ISSUE THREAD

**Issue by jaronheard** [Jobs-Economy/raise-effect#8]

**Comment by jaronheard** [comment]
- SliderBox - holds the state of the value of the wage slider 
  - Slider - interactive component, updates state of SliderBox
  - SliderTooltip
  - MapBox - holds the state for the selected family type and selected geographic region, pulls data from the API
    - Map - interactive component, updates state of MapBox for selected geographic region
      - MapSelector
    - Households - interactive component, updates state of MapBox for selected family type
      - Household1
      - Household2
      - Household3
    - Impact

**Comment by jaronheard** [comment]
![CompenentDiagram](http://i.imgur.com/KcjZKsQ.png?1)

**Comment by browniefed** [comment]
We did this.
